# Generated by Django 5.2 on 2025-05-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattempt',
            name='grading_period',
            field=models.CharField(blank=True, choices=[('prelim', 'Prelim'), ('midterm', 'Midterm'), ('prefinal', 'Prefinal'), ('final', 'Final')], help_text='Cached grading period for dashboard filtering', max_length=10, null=True),
        ),
    ]
