# Generated by Django 5.2 on 2025-05-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_exam_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examquestion',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('identification', 'Identification'), ('fill_in_the_blanks', 'Fill in the Blanks')], default='multiple_choice', max_length=20),
        ),
    ]
