# Generated by Django 5.2 on 2025-05-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_examquestion_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='examuseranswer',
            name='partial_score',
            field=models.PositiveIntegerField(default=0, help_text='Number of correct blanks for fill-in-the-blanks questions'),
        ),
    ]
