# Generated by Django 5.2 on 2025-05-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examuseranswer_partial_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examquestion',
            options={},
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='order',
        ),
    ]
