# Generated by Django 5.2 on 2025-05-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockedQuizPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('prelim', 'Prelim'), ('midterm', 'Midterm'), ('prefinal', 'Prefinal'), ('final', 'Final')], max_length=10, unique=True)),
                ('locked', models.BooleanField(default=True)),
                ('locked_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Locked Quiz Period',
                'verbose_name_plural': 'Locked Quiz Periods',
                'ordering': ['period'],
            },
        ),
    ]
