# Generated by Django 5.2 on 2025-05-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_lockedquizperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='locked',
            field=models.BooleanField(default=False, help_text='Lock this quiz for non-admin users'),
        ),
    ]
