# Generated by Django 5.2 on 2025-05-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quizattempt_grading_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='raw_points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='total_points',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
