# Generated by Django 5.2 on 2025-05-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_remove_lesson_category_remove_lesson_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='grading_period',
            field=models.CharField(choices=[('prelim', 'Prelim'), ('midterm', 'Midterm'), ('prefinal', 'Prefinal'), ('final', 'Final')], default='prelim', max_length=10),
        ),
    ]
