# Generated by Django 5.2 on 2025-05-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_periodlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='html_content',
            field=models.TextField(blank=True, help_text='Auto-generated HTML from .docx if available', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
